// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";
import "./UMAInterfaces.sol";

interface ISangomaOracle {
    function resolveMarket(bytes32 questionId, uint[] calldata payouts) external;
}

/**
 * @title UMAResolutionModule
 * @dev This module allows Sangoma prediction markets to be resolved using UMA's Optimistic Oracle V3.
 */
contract UMAResolutionModule is Ownable {
    IOptimisticOracleV3 public immutable oracle;
    ISangomaOracle public immutable sangomaOracle;

    // Mapping from UMA assertionId to Sangoma questionId (marketId)
    mapping(bytes32 => bytes32) public assertionToMarket;
    // Mapping from marketId to UMA assertionId
    mapping(bytes32 => bytes32) public marketToAssertion;

    event MarketAssertionMade(bytes32 indexed marketId, bytes32 indexed assertionId, string claim);
    event MarketSettledOnUMA(bytes32 indexed marketId, bytes32 indexed assertionId, bool success);

    constructor(address _umaOracle, address _sangomaOracle) Ownable(msg.sender) {
        oracle = IOptimisticOracleV3(_umaOracle);
        sangomaOracle = ISangomaOracle(_sangomaOracle);
    }

    /**
     * @dev Asserts a market outcome on UMA.
     * @param marketId The unique identifier of the Sangoma market.
     * @param claim The human-readable claim being asserted.
     * @param currency The ERC-20 token used for the bond.
     * @param bond The amount of tokens posted as a bond.
     * @return assertionId The unique ID generated by UMA for this assertion.
     */
    function assertMarketOutcome(
        bytes32 marketId,
        string calldata claim,
        address currency,
        uint256 bond
    ) external returns (bytes32 assertionId) {
        // Transfer bond from sender to this contract
        IERC20(currency).transferFrom(msg.sender, address(this), bond);
        // Approve oracle to spend bond
        IERC20(currency).approve(address(oracle), bond);

        assertionId = oracle.assertTruth(
            bytes(claim),
            msg.sender, // asserter
            address(this), // callbackRecipient
            address(0), // escalationManager
            7200, // liveness
            currency,
            bond,
            keccak256("ASSERT_TRUTH"), // identifier
            bytes32(0) // domainId
        );

        assertionToMarket[assertionId] = marketId;
        marketToAssertion[marketId] = assertionId;

        emit MarketAssertionMade(marketId, assertionId, claim);
    }

    /**
     * @dev Callback function called when an assertion is settled on UMA.
     * @param assertionId The ID of the assertion being settled.
     * @param assertedTruth Whether the assertion was successful.
     */
    function assertionResolvedCallback(bytes32 assertionId, bool assertedTruth) external {
        require(msg.sender == address(oracle), "Only UMA Oracle can call");
        
        bytes32 marketId = assertionToMarket[assertionId];
        if (marketId != bytes32(0)) {
            emit MarketSettledOnUMA(marketId, assertionId, assertedTruth);
        }
    }

    /**
     * @dev Resolves the Sangoma market based on the settled UMA assertion.
     * @param marketId The Sangoma market to resolve.
     */
    function resolveSangomaMarket(bytes32 marketId) external {
        bytes32 assertionId = marketToAssertion[marketId];
        require(assertionId != bytes32(0), "No assertion for market");

        // Try to settle if not already settled
        try oracle.settleAndGetAssertionResult(assertionId) {} catch {}

        IOptimisticOracleV3.Assertion memory assertion = oracle.getAssertion(assertionId);
        require(assertion.settled, "Assertion not settled");
        require(assertion.settlementSuccessful, "Assertion failed");

        // In the pilot, we assume a successful assertion resolves the market to YES (1, 0)
        uint[] memory payouts = new uint[](2);
        payouts[0] = 1; // YES
        payouts[1] = 0; // NO

        sangomaOracle.resolveMarket(marketId, payouts);
    }
}
